/*
 * Feature detection for libstdc++ is often inconsistent. Some features are
 * detected correctly for a given GCC version but fail in others, or work in
 * native builds but fail during Canadian cross builds.
 *
 * Instead of trying to fix each individual detection failure, we explicitly
 * define the features that are known to be available.
 */

#ifndef _OBGGCC_CXX_CONFIG_H
#define _OBGGCC_CXX_CONFIG_H 1

#undef _GLIBCXX_HAVE_ACOSF
#define _GLIBCXX_HAVE_ACOSF 1

#undef _GLIBCXX_HAVE_ACOSL
#define _GLIBCXX_HAVE_ACOSL 1

#undef _GLIBCXX_HAVE_ASINF
#define _GLIBCXX_HAVE_ASINF 1

#undef _GLIBCXX_HAVE_ASINL
#define _GLIBCXX_HAVE_ASINL 1

#undef _GLIBCXX_HAVE_ATANF
#define _GLIBCXX_HAVE_ATANF 1

#undef _GLIBCXX_HAVE_ATANL
#define _GLIBCXX_HAVE_ATANL 1

#undef _GLIBCXX_HAVE_ATAN2F
#define _GLIBCXX_HAVE_ATAN2F 1

#undef _GLIBCXX_HAVE_ATAN2L
#define _GLIBCXX_HAVE_ATAN2L 1

#undef _GLIBCXX_HAVE_CEILF
#define _GLIBCXX_HAVE_CEILF 1

#undef _GLIBCXX_HAVE_CEILL
#define _GLIBCXX_HAVE_CEILL 1

#undef _GLIBCXX_HAVE_COSF
#define _GLIBCXX_HAVE_COSF 1

#undef _GLIBCXX_HAVE_COSL
#define _GLIBCXX_HAVE_COSL 1

#undef _GLIBCXX_HAVE_COSHF
#define _GLIBCXX_HAVE_COSHF 1

#undef _GLIBCXX_HAVE_COSHL
#define _GLIBCXX_HAVE_COSHL 1

#undef _GLIBCXX_HAVE_EXPF
#define _GLIBCXX_HAVE_EXPF 1

#undef _GLIBCXX_HAVE_EXPL
#define _GLIBCXX_HAVE_EXPL 1

#undef _GLIBCXX_HAVE_FABSF
#define _GLIBCXX_HAVE_FABSF 1

#undef _GLIBCXX_HAVE_FABSL
#define _GLIBCXX_HAVE_FABSL 1

#undef _GLIBCXX_HAVE_FLOORF
#define _GLIBCXX_HAVE_FLOORF 1

#undef _GLIBCXX_HAVE_FLOORL
#define _GLIBCXX_HAVE_FLOORL 1

#undef _GLIBCXX_HAVE_FMODF
#define _GLIBCXX_HAVE_FMODF 1

#undef _GLIBCXX_HAVE_FMODL
#define _GLIBCXX_HAVE_FMODL 1

#undef _GLIBCXX_HAVE_FREXPF
#define _GLIBCXX_HAVE_FREXPF 1

#undef _GLIBCXX_HAVE_FREXPL
#define _GLIBCXX_HAVE_FREXPL 1

#undef _GLIBCXX_HAVE_LDEXPF
#define _GLIBCXX_HAVE_LDEXPF 1

#undef _GLIBCXX_HAVE_LDEXPL
#define _GLIBCXX_HAVE_LDEXPL 1

#undef _GLIBCXX_HAVE_LOGF
#define _GLIBCXX_HAVE_LOGF 1

#undef _GLIBCXX_HAVE_LOGL
#define _GLIBCXX_HAVE_LOGL 1

#undef _GLIBCXX_HAVE_LOG10F
#define _GLIBCXX_HAVE_LOG10F 1

#undef _GLIBCXX_HAVE_LOG10L
#define _GLIBCXX_HAVE_LOG10L 1

#undef _GLIBCXX_HAVE_MODF
#define _GLIBCXX_HAVE_MODF 1

#undef _GLIBCXX_HAVE_MODFF
#define _GLIBCXX_HAVE_MODFF 1

#undef _GLIBCXX_HAVE_MODFL
#define _GLIBCXX_HAVE_MODFL 1

#undef _GLIBCXX_HAVE_POWF
#define _GLIBCXX_HAVE_POWF 1

#undef _GLIBCXX_HAVE_POWL
#define _GLIBCXX_HAVE_POWL 1

#undef _GLIBCXX_HAVE_SINF
#define _GLIBCXX_HAVE_SINF 1

#undef _GLIBCXX_HAVE_SINL
#define _GLIBCXX_HAVE_SINL 1

#undef _GLIBCXX_HAVE_SINHF
#define _GLIBCXX_HAVE_SINHF 1

#undef _GLIBCXX_HAVE_SINHL
#define _GLIBCXX_HAVE_SINHL 1

#undef _GLIBCXX_HAVE_SQRTF
#define _GLIBCXX_HAVE_SQRTF 1

#undef _GLIBCXX_HAVE_SQRTL
#define _GLIBCXX_HAVE_SQRTL 1

#undef _GLIBCXX_HAVE_TANF
#define _GLIBCXX_HAVE_TANF 1

#undef _GLIBCXX_HAVE_TANL
#define _GLIBCXX_HAVE_TANL 1

#undef _GLIBCXX_HAVE_TANHF
#define _GLIBCXX_HAVE_TANHF 1

#undef _GLIBCXX_HAVE_TANHL
#define _GLIBCXX_HAVE_TANHL 1

#undef _GLIBCXX_HAVE_WCSTOF
#define _GLIBCXX_HAVE_WCSTOF 1

#undef _GLIBCXX_HAVE_HYPOTL
#define _GLIBCXX_HAVE_HYPOTL 1

#undef _GLIBCXX_HAVE_FINITE
#define _GLIBCXX_HAVE_FINITE 1

#undef _GLIBCXX_HAVE_FINITEF
#define _GLIBCXX_HAVE_FINITEF 1

#undef _GLIBCXX_HAVE_FINITEL
#define _GLIBCXX_HAVE_FINITEL 1

#undef _GLIBCXX_USE_C99_CTYPE
#define _GLIBCXX_USE_C99_CTYPE 1

#undef _GLIBCXX_USE_C99_FENV
#define _GLIBCXX_USE_C99_FENV 1

#undef _GLIBCXX_USE_C99_INTTYPES
#define _GLIBCXX_USE_C99_INTTYPES 1

#undef _GLIBCXX_USE_C99_INTTYPES_WCHAR_T
#define _GLIBCXX_USE_C99_INTTYPES_WCHAR_T 1

#undef _GLIBCXX_USE_C99_STDINT
#define _GLIBCXX_USE_C99_STDINT 1

#undef _GLIBCXX_USE_FSEEKO_FTELLO
#define _GLIBCXX_USE_FSEEKO_FTELLO 1

#undef _GLIBCXX_HAVE_SETENV
#define _GLIBCXX_HAVE_SETENV 1

#undef _GLIBCXX_HAVE_SECURE_GETENV
#define _GLIBCXX_HAVE_SECURE_GETENV 1

#undef _GLIBCXX_HAVE_DECL_STRNLEN
#define _GLIBCXX_HAVE_DECL_STRNLEN 1

#undef _GLIBCXX_HAVE_ICONV
#define _GLIBCXX_HAVE_ICONV 1

#undef _GLIBCXX_ICONV_CONST
#define _GLIBCXX_ICONV_CONST 1

#undef _GLIBCXX11_USE_C99_COMPLEX
#define _GLIBCXX11_USE_C99_COMPLEX 1

#undef _GLIBCXX_USE_C99_COMPLEX_ARC
#define _GLIBCXX_USE_C99_COMPLEX_ARC 1

#undef _GLIBCXX_HAVE_TLS
#define _GLIBCXX_HAVE_TLS 1

#undef _GLIBCXX_USE_DEV_RANDOM
#define _GLIBCXX_USE_DEV_RANDOM 1

#undef _GLIBCXX_HAVE_C99_FLT_EVAL_TYPES
#define _GLIBCXX_HAVE_C99_FLT_EVAL_TYPES 1

#undef _GLIBCXX_HAVE_LSEEK
#define _GLIBCXX_HAVE_LSEEK 1

#undef _GLIBCXX_HAVE_LINK_H
#define _GLIBCXX_HAVE_LINK_H 1

#undef _GLIBCXX_HAVE_SYS_MMAN_H
#define _GLIBCXX_HAVE_SYS_MMAN_H 1

#undef _GLIBCXX_USE_CHDIR
#define _GLIBCXX_USE_CHDIR 1

#undef _GLIBCXX_USE_CHMOD
#define _GLIBCXX_USE_CHMOD 1

#undef _GLIBCXX_USE_GETCWD
#define _GLIBCXX_USE_GETCWD 1

#undef _GLIBCXX_USE_MKDIR
#define _GLIBCXX_USE_MKDIR 1

#undef _GLIBCXX_HAVE_DIRFD
#define _GLIBCXX_HAVE_DIRFD 1

#undef _GLIBCXX_HAVE_LIBINTL_H
#define _GLIBCXX_HAVE_LIBINTL_H 1

#undef _GLIBCXX_USE_NLS
#define _GLIBCXX_USE_NLS 1

#undef _GLIBCXX_USE_STRUCT_TM_TM_ZONE
#define _GLIBCXX_USE_STRUCT_TM_TM_ZONE 1

#undef _GLIBCXX_HAVE_FWRITE_UNLOCKED
#define _GLIBCXX_HAVE_FWRITE_UNLOCKED 1

#undef _GLIBCXX_HAVE_MEMALIGN
#define _GLIBCXX_HAVE_MEMALIGN 1

#undef _GLIBCXX_HAVE_POSIX_MEMALIGN
#define _GLIBCXX_HAVE_POSIX_MEMALIGN 1

#undef _GLIBCXX_HAVE_O_NONBLOCK
#define _GLIBCXX_HAVE_O_NONBLOCK 1

#undef _GLIBCXX_HAVE_POSIX_SEMAPHORE
#define _GLIBCXX_HAVE_POSIX_SEMAPHORE 1

#undef _GLIBCXX_HAVE_SOCKATMARK
#define _GLIBCXX_HAVE_SOCKATMARK 1

#undef _GLIBCXX_HAVE_SYS_PTRACE_H
#define _GLIBCXX_HAVE_SYS_PTRACE_H 1

#undef _GLIBCXX_HAVE_USELOCALE
#define _GLIBCXX_HAVE_USELOCALE 1

#undef _GLIBCXX_ATOMIC_WORD_BUILTINS
#define _GLIBCXX_ATOMIC_WORD_BUILTINS 1

#undef _GLIBCXX_USE_GLIBC_STDIO_EXT
#define _GLIBCXX_USE_GLIBC_STDIO_EXT 1

#undef _GLIBCXX_USE_PROC_SELF_STATUS
#define _GLIBCXX_USE_PROC_SELF_STATUS 1

#undef _GLIBCXX_USE_PTRACE
#define _GLIBCXX_USE_PTRACE 1

#undef _GLIBCXX_USE_RANDOM_TR1
#define _GLIBCXX_USE_RANDOM_TR1 1

#undef _GLIBCXX_USE_STDIO_LOCKING
#define _GLIBCXX_USE_STDIO_LOCKING 1

#undef _GLIBCXX_USE_NL_LANGINFO_L
#define _GLIBCXX_USE_NL_LANGINFO_L 1

#if __GLIBC_PREREQ(2, 35)
	#undef _GLIBCXX_USE_COPY_FILE_RANGE
	#define _GLIBCXX_USE_COPY_FILE_RANGE 1
#endif

#if __GLIBC_PREREQ(2, 36)
	#undef _GLIBCXX_HAVE_ARC4RANDOM
	#define _GLIBCXX_HAVE_ARC4RANDOM 1
#endif

#if __GLIBC_PREREQ(2, 17)
	#undef _GLIBCXX_HAVE_ALIGNED_ALLOC
	#define _GLIBCXX_HAVE_ALIGNED_ALLOC 1
	
	#undef _GLIBCXX_HAVE_TIMESPEC_GET
	#define _GLIBCXX_HAVE_TIMESPEC_GET 1
	
	#undef _GLIBCXX_HAVE_UCHAR_H
	#define _GLIBCXX_HAVE_UCHAR_H 1
	
	#undef _GLIBCXX_USE_C11_UCHAR_CXX11
	#define _GLIBCXX_USE_C11_UCHAR_CXX11 1
	
	#undef _GLIBCXX_USE_UCHAR_C8RTOMB_MBRTOC8_CXX20
	#define _GLIBCXX_USE_UCHAR_C8RTOMB_MBRTOC8_CXX20 1
	
	#undef _GLIBCXX_USE_UCHAR_C8RTOMB_MBRTOC8_FCHAR8_T
	#define _GLIBCXX_USE_UCHAR_C8RTOMB_MBRTOC8_FCHAR8_T 1
#endif

#if __GLIBC_PREREQ(2, 11)
	#undef _GLIBCXX_HAVE_AT_QUICK_EXIT
	#define _GLIBCXX_HAVE_AT_QUICK_EXIT 1
	
	#undef _GLIBCXX_HAVE_QUICK_EXIT
	#define _GLIBCXX_HAVE_QUICK_EXIT 1
#endif

#if __GLIBC_PREREQ(2, 7)
	#undef _GLIBCXX_HAVE_OPENAT
	#define _GLIBCXX_HAVE_OPENAT 1
	
	#undef _GLIBCXX_HAVE_STRERROR_L
	#define _GLIBCXX_HAVE_STRERROR_L 1
	
	#undef _GLIBCXX_HAVE_FDOPENDIR
	#define _GLIBCXX_HAVE_FDOPENDIR 1
	
	#undef _GLIBCXX_HAVE_UNLINKAT
	#define _GLIBCXX_HAVE_UNLINKAT 1
	
	#undef _GLIBCXX_USE_FCHMODAT
	#define _GLIBCXX_USE_FCHMODAT 1
	
	#undef _GLIBCXX_USE_UTIMENSAT
	#define _GLIBCXX_USE_UTIMENSAT 1
#endif

#if __GLIBC_PREREQ(2, 27)
	#undef _GLIBCXX_HAVE_GETENTROPY
	#define _GLIBCXX_HAVE_GETENTROPY 1
#endif

#if __GLIBC_PREREQ(2, 19)
	#undef _GLIBCXX_HAVE___CXA_THREAD_ATEXIT
	#define _GLIBCXX_HAVE___CXA_THREAD_ATEXIT 1
	
	#undef _GLIBCXX_HAVE___CXA_THREAD_ATEXIT_IMPL
	#define _GLIBCXX_HAVE___CXA_THREAD_ATEXIT_IMPL 1
#endif

#if __GLIBC_PREREQ(2, 31)
	#undef _GLIBCXX_USE_PTHREAD_COND_CLOCKWAIT
	#define _GLIBCXX_USE_PTHREAD_COND_CLOCKWAIT 1
	
	#undef _GLIBCXX_USE_PTHREAD_MUTEX_CLOCKLOCK
	#define _GLIBCXX_USE_PTHREAD_MUTEX_CLOCKLOCK 1
	
	#undef _GLIBCXX_USE_PTHREAD_RWLOCK_CLOCKLOCK
	#define _GLIBCXX_USE_PTHREAD_RWLOCK_CLOCKLOCK 1
#endif

#endif
