#ifndef _OBGGCC_CXX_CONFIG_H
#define _OBGGCC_CXX_CONFIG_H 1

#undef _GLIBCXX_HAVE_ACOSF
#define _GLIBCXX_HAVE_ACOSF 1

#undef _GLIBCXX_HAVE_ACOSL
#define _GLIBCXX_HAVE_ACOSL 1

#undef _GLIBCXX_HAVE_ASINF
#define _GLIBCXX_HAVE_ASINF 1

#undef _GLIBCXX_HAVE_ASINL
#define _GLIBCXX_HAVE_ASINL 1

#undef _GLIBCXX_HAVE_ATANF
#define _GLIBCXX_HAVE_ATANF 1

#undef _GLIBCXX_HAVE_ATANL
#define _GLIBCXX_HAVE_ATANL 1

#undef _GLIBCXX_HAVE_ATAN2F
#define _GLIBCXX_HAVE_ATAN2F 1

#undef _GLIBCXX_HAVE_ATAN2L
#define _GLIBCXX_HAVE_ATAN2L 1

#undef _GLIBCXX_HAVE_CEILF
#define _GLIBCXX_HAVE_CEILF 1

#undef _GLIBCXX_HAVE_CEILL
#define _GLIBCXX_HAVE_CEILL 1

#undef _GLIBCXX_HAVE_COSF
#define _GLIBCXX_HAVE_COSF 1

#undef _GLIBCXX_HAVE_COSL
#define _GLIBCXX_HAVE_COSL 1

#undef _GLIBCXX_HAVE_COSHF
#define _GLIBCXX_HAVE_COSHF 1

#undef _GLIBCXX_HAVE_COSHL
#define _GLIBCXX_HAVE_COSHL 1

#undef _GLIBCXX_HAVE_EXPF
#define _GLIBCXX_HAVE_EXPF 1

#undef _GLIBCXX_HAVE_EXPL
#define _GLIBCXX_HAVE_EXPL 1

#undef _GLIBCXX_HAVE_FABSF
#define _GLIBCXX_HAVE_FABSF 1

#undef _GLIBCXX_HAVE_FABSL
#define _GLIBCXX_HAVE_FABSL 1

#undef _GLIBCXX_HAVE_FLOORF
#define _GLIBCXX_HAVE_FLOORF 1

#undef _GLIBCXX_HAVE_FLOORL
#define _GLIBCXX_HAVE_FLOORL 1

#undef _GLIBCXX_HAVE_FMODF
#define _GLIBCXX_HAVE_FMODF 1

#undef _GLIBCXX_HAVE_FMODL
#define _GLIBCXX_HAVE_FMODL 1

#undef _GLIBCXX_HAVE_FREXPF
#define _GLIBCXX_HAVE_FREXPF 1

#undef _GLIBCXX_HAVE_FREXPL
#define _GLIBCXX_HAVE_FREXPL 1

#undef _GLIBCXX_HAVE_LDEXPF
#define _GLIBCXX_HAVE_LDEXPF 1

#undef _GLIBCXX_HAVE_LDEXPL
#define _GLIBCXX_HAVE_LDEXPL 1

#undef _GLIBCXX_HAVE_LOGF
#define _GLIBCXX_HAVE_LOGF 1

#undef _GLIBCXX_HAVE_LOGL
#define _GLIBCXX_HAVE_LOGL 1

#undef _GLIBCXX_HAVE_LOG10F
#define _GLIBCXX_HAVE_LOG10F 1

#undef _GLIBCXX_HAVE_LOG10L
#define _GLIBCXX_HAVE_LOG10L 1

#undef _GLIBCXX_HAVE_MODFF
#define _GLIBCXX_HAVE_MODFF 1

#undef _GLIBCXX_HAVE_MODFL
#define _GLIBCXX_HAVE_MODFL 1

#undef _GLIBCXX_HAVE_POWF
#define _GLIBCXX_HAVE_POWF 1

#undef _GLIBCXX_HAVE_POWL
#define _GLIBCXX_HAVE_POWL 1

#undef _GLIBCXX_HAVE_SINF
#define _GLIBCXX_HAVE_SINF 1

#undef _GLIBCXX_HAVE_SINL
#define _GLIBCXX_HAVE_SINL 1

#undef _GLIBCXX_HAVE_SINHF
#define _GLIBCXX_HAVE_SINHF 1

#undef _GLIBCXX_HAVE_SINHL
#define _GLIBCXX_HAVE_SINHL 1

#undef _GLIBCXX_HAVE_SQRTF
#define _GLIBCXX_HAVE_SQRTF 1

#undef _GLIBCXX_HAVE_SQRTL
#define _GLIBCXX_HAVE_SQRTL 1

#undef _GLIBCXX_HAVE_TANF
#define _GLIBCXX_HAVE_TANF 1

#undef _GLIBCXX_HAVE_TANL
#define _GLIBCXX_HAVE_TANL 1

#undef _GLIBCXX_HAVE_TANHF
#define _GLIBCXX_HAVE_TANHF 1

#undef _GLIBCXX_HAVE_TANHL
#define _GLIBCXX_HAVE_TANHL 1

#undef _GLIBCXX_HAVE_WCSTOF
#define _GLIBCXX_HAVE_WCSTOF 1

#undef _GLIBCXX_HAVE_HYPOTL
#define _GLIBCXX_HAVE_HYPOTL 1

#endif
