set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_PROCESSOR "i386")

set(TARGET_GLIBC "2.23")
set(TOOLCHAIN_PREFIX "${CMAKE_SYSTEM_PROCESSOR}-unknown-linux-gnu")

set(TOOLCHAIN_PATH "$ENV{OBGGCC_HOME}")

if ("${TOOLCHAIN_PATH}" STREQUAL "")
	file(REAL_PATH "${CMAKE_CURRENT_LIST_DIR}" TOOLCHAIN_PATH)
	set(TOOLCHAIN_PATH "${TOOLCHAIN_PATH}/../../../../..")
endif()

set(CMAKE_C_COMPILER "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}${TARGET_GLIBC}-gcc" CACHE FILEPATH "cc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}${TARGET_GLIBC}-g++" CACHE FILEPATH "c++")
set(CMAKE_AR "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-ar" CACHE FILEPATH "ar")
set(CMAKE_RANLIB "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-ranlib" CACHE FILEPATH "ranlib")
set(CMAKE_STRIP "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-strip" CACHE FILEPATH "strip")
set(CMAKE_OBJCOPY "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-objcopy" CACHE FILEPATH "objcopy")
set(CMAKE_NM "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-nm" CACHE FILEPATH "nm")

set(OBGGCC_FIND_ROOT_PATH "${TOOLCHAIN_PATH}/${TOOLCHAIN_PREFIX}${TARGET_GLIBC};${NZ_FIND_ROOT_PATH}" CACHE FILEPATH "sysroot")

set(NZ "$ENV{OBGGCC_NZ}")
set(NZ_FIND_ROOT_PATH "")

if ("${NZ}" STREQUAL "1" OR "${NZ}" STREQUAL "true")
	set(NZ_FIND_ROOT_PATH "${TOOLCHAIN_PATH}/${TOOLCHAIN_PREFIX}${TARGET_GLIBC}/lib/nouzen/sysroot")
	
	set(PKG_CONFIG_EXECUTABLE "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}${TARGET_GLIBC}-pkg-config" CACHE FILEPATH "pkg-config")
else()
	set(PKG_CONFIG_EXECUTABLE "" CACHE FILEPATH "pkg-config")
endif()

set(CMAKE_FIND_ROOT_PATH "${OBGGCC_FIND_ROOT_PATH};${NZ_FIND_ROOT_PATH}" CACHE FILEPATH "sysroot")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
